### ISSUE TITLE
Login question in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by cmsoneself** [dotnet-express/AdminLTE-Starter-Kit#1]
Dear friend,because of the ASP.NET Core has builted in the Login Page,how to migrate the Acount Page which is designed in your project to the ASP.NET Core 2.1 project.

**Comment by leonex** [comment]
See [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio).

ASP.NET Core 2.1 and later provides [ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1) as a [Razor Class Library](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1).

You need:
1. From Solution Explorer, right-click on the project > Add > New Scaffolded Item.
2. From the left pane of the Add Scaffold dialog, select Identity > ADD.
3. In the ADD Identity dialog, select **Override all files**.

After that, you can modify files from this project.

**In version 0.8.1 we plan add ASP.NET Core 2.1 support (with Identity and other features)**
